# -*- coding: utf-8 -*-
"""Hospital Management System: Data Analysis and Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Utfci4cNX-z9TwpMOrebCrRtrpWpeL9Q
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Sample Data: Hospital Management System
data = {
    "Patient_ID": [101, 102, 103, 104, 105, 106],
    "Age": [25, 45, 35, 60, 29, 50],
    "Gender": ["Male", "Female", "Female", "Male", "Male", "Female"],
    "Department": ["Cardiology", "Neurology", "Orthopedics", "Cardiology", "General", "Neurology"],
    "Days_Admitted": [4, 10, 3, 7, 2, 12],
    "Cost": [1500, 4000, 1200, 3000, 800, 5000]
}

# Convert the dictionary to a DataFrame
df = pd.DataFrame(data)

# Preview the dataset
print("Hospital Management Data:")
print(df)

# -----------------------------
# Data Analysis
# -----------------------------

# 1. Average Cost by Department
avg_cost_by_department = df.groupby("Department")["Cost"].mean()
print("\nAverage Cost by Department:")
print(avg_cost_by_department)

# 2. Gender Distribution
gender_distribution = df["Gender"].value_counts()
print("\nGender Distribution:")
print(gender_distribution)

# 3. Average Days Admitted by Age Group
df["Age_Group"] = pd.cut(df["Age"], bins=[0, 30, 50, 100], labels=["0-30", "31-50", "51+"])
avg_days_by_age_group = df.groupby("Age_Group")["Days_Admitted"].mean()
print("\nAverage Days Admitted by Age Group:")
print(avg_days_by_age_group)

# -----------------------------
# Data Visualization
# -----------------------------

# Plot 1: Cost Analysis by Department
plt.figure(figsize=(8, 6))
sns.barplot(x=avg_cost_by_department.index, y=avg_cost_by_department.values, palette="viridis")
plt.title("Average Cost by Department")
plt.ylabel("Average Cost ($)")
plt.xlabel("Department")
plt.show()

# Plot 2: Gender Distribution
plt.figure(figsize=(6, 6))
gender_distribution.plot(kind="pie", autopct='%1.1f%%', colors=["skyblue", "lightpink"])
plt.title("Gender Distribution")
plt.ylabel("")  # Hide y-axis label
plt.show()

# Plot 3: Days Admitted by Age Group
plt.figure(figsize=(8, 6))
sns.barplot(x=avg_days_by_age_group.index, y=avg_days_by_age_group.values, palette="coolwarm")
plt.title("Average Days Admitted by Age Group")
plt.ylabel("Average Days")
plt.xlabel("Age Group")
plt.show()

# -----------------------------
# Additional Insights
# -----------------------------

# 1. Total cost and average days admitted per patient
df["Cost_Per_Day"] = df["Cost"] / df["Days_Admitted"]
print("\nCost per Day for Each Patient:")
print(df[["Patient_ID", "Cost_Per_Day"]])

# 2. Highest cost patient
highest_cost_patient = df[df["Cost"] == df["Cost"].max()]
print("\nHighest Cost Patient:")
print(highest_cost_patient)

# 3. Department with maximum patients
department_max_patients = df["Department"].value_counts().idxmax()
print("\nDepartment with Maximum Patients:")
print(department_max_patients)